services:
  carsstorageapi:
    image: carsstorageapi-211283
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:443"  
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=CarsStorage;Username=postgres;Password=pgroot; 
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: CarsStorage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgroot
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgres



