

networks:
  carsstorageapi-network:
    driver: bridge

services:
  carsstorageapi:
    image: carsstorageapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5243:80"  
      - "7251:443"  
    depends_on:
      - db
    networks:
      - carsstorageapi-network

  db:
    image: postgres:latest
    container_name: carsstorageapi
    restart: always
    environment:
      POSTGRES_DB: carsstorage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgroot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - carsstorageapi-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  pgdata:


